# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI_choose.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ChooseWindow(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(384, 300)
        self.add_button = QtWidgets.QPushButton(Form)
        self.add_button.setGeometry(QtCore.QRect(290, 10, 75, 23))
        self.add_button.setObjectName("add_button")
        self.add_line_edit = QtWidgets.QLineEdit(Form)
        self.add_line_edit.setGeometry(QtCore.QRect(10, 10, 261, 20))
        self.add_line_edit.setObjectName("add_line_edit")
        self.delete_button = QtWidgets.QPushButton(Form)
        self.delete_button.setGeometry(QtCore.QRect(290, 40, 75, 23))
        self.delete_button.setObjectName("delete_button")
        self.listWidget = QtWidgets.QListWidget(Form)
        self.listWidget.setGeometry(QtCore.QRect(10, 40, 261, 241))
        self.listWidget.setObjectName("listWidget")

        self.visual_smooth_line_button = QtWidgets.QPushButton(Form)
        self.visual_smooth_line_button.setGeometry(QtCore.QRect(290, 70, 75, 23))
        self.visual_smooth_line_button.setObjectName("pushButton_3")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "存储用户UID"))
        self.add_button.setText(_translate("Form", "添加"))
        self.delete_button.setText(_translate("Form", "删除"))
        self.visual_smooth_line_button.setText(_translate("Form", "平滑折线图"))
